package migration

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

type HTMLParser struct {
	PostMap map[string]PostInfo
}

func NewHTMLParser() *HTMLParser {
	return &HTMLParser{
		PostMap: make(map[string]PostInfo),
	}
}

// ParseIndexHTML parses the bdfr-html index.html file to extract post metadata.
//
// Expected index.html structure (generated by bdfr-html):
//
//	Each post is contained in a <div class="post"> block containing:
//	  - <a href="{POSTID}.html"> - links to the post's HTML file
//	  - <span class="subreddit">r/{SUBREDDIT}</span> - the subreddit name
//	  - <span class="user">u/{USERNAME}</span> - the post author's username
//
// The function reads the entire file and uses regex to extract all post IDs,
// subreddits, and usernames, correlating them by position in the file.
func (p *HTMLParser) ParseIndexHTML(indexPath string) error {
	content, err := os.ReadFile(indexPath)
	if err != nil {
		return fmt.Errorf("open index.html: %w", err)
	}

	contentStr := string(content)

	postLinkPattern := regexp.MustCompile(`<a\s+href="([a-zA-Z0-9]+)\.html"`)
	subredditPattern := regexp.MustCompile(`<span\s+class="subreddit"[^>]*>r/([^<]+)</span>`)
	userPattern := regexp.MustCompile(`<span\s+class="user"[^>]*>u/([^<]+)</span>`)

	// Find all matches with their byte positions
	postMatches := postLinkPattern.FindAllStringSubmatchIndex(contentStr, -1)
	subredditMatches := subredditPattern.FindAllStringSubmatchIndex(contentStr, -1)
	userMatches := userPattern.FindAllStringSubmatchIndex(contentStr, -1)

	type match struct {
		value string
		pos   int
	}

	// Convert subreddit matches to structured data
	var subreddits []match
	for _, m := range subredditMatches {
		if len(m) >= 4 {
			subreddits = append(subreddits, match{
				value: contentStr[m[2]:m[3]],
				pos:   m[0],
			})
		}
	}

	// Convert user matches to structured data
	var users []match
	for _, m := range userMatches {
		if len(m) >= 4 {
			users = append(users, match{
				value: contentStr[m[2]:m[3]],
				pos:   m[0],
			})
		}
	}

	// Process each post link, finding the closest subreddit and user span
	// Using two-pointer approach for O(n) complexity
	subIdx, userIdx := 0, 0
	for _, pm := range postMatches {
		if len(pm) < 4 {
			continue
		}

		postID := contentStr[pm[2]:pm[3]]
		postPos := pm[0]

		// Advance subIdx to first subreddit after postPos
		for subIdx < len(subreddits) && subreddits[subIdx].pos <= postPos {
			subIdx++
		}
		var subreddit string
		if subIdx < len(subreddits) {
			subreddit = subreddits[subIdx].value
		}

		// Advance userIdx to first user after postPos
		for userIdx < len(users) && users[userIdx].pos <= postPos {
			userIdx++
		}
		var username string
		if userIdx < len(users) {
			username = users[userIdx].value
		}

		if subreddit != "" {
			p.addPost(postID, subreddit, username)
		}
	}

	return nil
}

func (p *HTMLParser) addPost(postID, subreddit, username string) {
	cleanSubreddit := strings.TrimPrefix(subreddit, "r/")
	isUserPost := strings.HasPrefix(cleanSubreddit, "u_")

	p.PostMap[postID] = PostInfo{
		PostID:     postID,
		Subreddit:  cleanSubreddit,
		Username:   username,
		IsUserPost: isUserPost,
	}
}
