package migration

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// isPathWithin checks if targetPath is within baseDir to prevent path traversal attacks.
// Returns true if targetPath is the same as or a subdirectory of baseDir.
func isPathWithin(baseDir, targetPath string) bool {
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return false
	}
	absTarget, err := filepath.Abs(targetPath)
	if err != nil {
		return false
	}
	// Ensure base ends with separator for proper prefix check
	if !strings.HasSuffix(absBase, string(filepath.Separator)) {
		absBase += string(filepath.Separator)
	}
	return strings.HasPrefix(absTarget, absBase) || absTarget == filepath.Clean(baseDir)
}

// HTMLParser parses bdfr-html files to extract post metadata.
type HTMLParser struct {
	PostMap map[string]PostInfo
}

// NewHTMLParser creates a new HTMLParser instance.
func NewHTMLParser() *HTMLParser {
	return &HTMLParser{
		PostMap: make(map[string]PostInfo),
	}
}

// ParseIndexHTML parses the bdfr-html index.html file to extract post metadata.
//
// Expected index.html structure (generated by bdfr-html):
//
//	Each post is contained in a <div class="post"> block containing:
//	  - <a href="{POSTID}.html"> - links to the post's HTML file
//	  - <span class="subreddit">r/{SUBREDDIT}</span> - the subreddit name
//	  - <span class="user">u/{USERNAME}</span> - the post author's username
//
// The function reads the entire file and uses regex to extract all post IDs,
// subreddits, and usernames, correlating them by position in the file.
func (p *HTMLParser) ParseIndexHTML(ctx context.Context, baseDir, indexPath string) error {
	if err := ctx.Err(); err != nil {
		return err
	}

	// Validate that indexPath is within baseDir to prevent path traversal
	if !isPathWithin(baseDir, indexPath) {
		return fmt.Errorf("index path %s is not within allowed directory %s", indexPath, baseDir)
	}

	content, err := os.ReadFile(indexPath)
	if err != nil {
		return fmt.Errorf("open index.html: %w", err)
	}

	p.PostMap = make(map[string]PostInfo)

	contentStr := string(content)

	postLinkPattern := regexp.MustCompile(`<a\s+href="([a-zA-Z0-9]+)\.html"`)
	subredditPattern := regexp.MustCompile(`<span\s+class="subreddit"[^>]*>r/([^<]+)</span>`)
	userPattern := regexp.MustCompile(`<span\s+class="user"[^>]*>u/([^<]+)</span>`)

	// Find all matches with their byte positions
	postMatches := postLinkPattern.FindAllStringSubmatchIndex(contentStr, -1)
	subredditMatches := subredditPattern.FindAllStringSubmatchIndex(contentStr, -1)
	userMatches := userPattern.FindAllStringSubmatchIndex(contentStr, -1)

	type match struct {
		value string
		pos   int
	}

	// Convert subreddit matches to structured data
	var subreddits []match
	for _, m := range subredditMatches {
		if len(m) >= 4 {
			subreddits = append(subreddits, match{
				value: contentStr[m[2]:m[3]],
				pos:   m[0],
			})
		}
	}

	// Convert user matches to structured data
	var users []match
	for _, m := range userMatches {
		if len(m) >= 4 {
			users = append(users, match{
				value: contentStr[m[2]:m[3]],
				pos:   m[0],
			})
		}
	}

	// Process each post link, finding the closest subreddit and user span
	// Using two-pointer approach for O(n) complexity
	subIdx, userIdx := 0, 0
	for _, pm := range postMatches {
		if len(pm) < 4 {
			continue
		}

		postID := contentStr[pm[2]:pm[3]]
		postPos := pm[0]

		// Advance subIdx to first subreddit after postPos
		for subIdx < len(subreddits) && subreddits[subIdx].pos <= postPos {
			subIdx++
		}
		var subreddit string
		if subIdx < len(subreddits) {
			subreddit = subreddits[subIdx].value
		}

		// Advance userIdx to first user after postPos
		for userIdx < len(users) && users[userIdx].pos <= postPos {
			userIdx++
		}
		var username string
		if userIdx < len(users) {
			username = users[userIdx].value
		}

		if subreddit != "" {
			p.addPost(postID, subreddit, username)
		}
	}

	return nil
}

func (p *HTMLParser) addPost(postID, subreddit, username string) {
	cleanSubreddit := strings.TrimPrefix(subreddit, "r/")
	isUserPost := strings.HasPrefix(cleanSubreddit, "u_")

	p.PostMap[postID] = PostInfo{
		PostID:     postID,
		Subreddit:  cleanSubreddit,
		Username:   username,
		IsUserPost: isUserPost,
	}
}

// ParseHTMLFile parses a single HTML file and extracts post metadata.
//
// Expected HTML file structure (generated by bdfr-html):
//
//	<span class="subreddit">r/{SUBREDDIT}</span>
//	<span class="user">u/{USERNAME}</span>
//
// The function extracts the POSTID from the filename (e.g., "1r4wjj5.html" → "1r4wjj5"),
// reads the HTML content, and uses regex to extract subreddit and username.
// Returns PostInfo with PostID, Subreddit, Username, and IsUserPost.
// IsUserPost is set to true when the subreddit starts with "u_".
// Returns error for file read failures or invalid filenames.
// Uses empty string if subreddit or username is missing (does not fail).
func (p *HTMLParser) ParseHTMLFile(ctx context.Context, filePath string) (PostInfo, error) {
	if err := ctx.Err(); err != nil {
		return PostInfo{}, err
	}

	filename := filepath.Base(filePath)
	ext := strings.ToLower(filepath.Ext(filename))
	if ext != ".html" {
		return PostInfo{}, fmt.Errorf("invalid file extension: %s", filename)
	}
	postID := strings.TrimSuffix(filename, filepath.Ext(filename))

	postIDPattern := regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)
	if postID == "" || !postIDPattern.MatchString(postID) {
		return PostInfo{}, fmt.Errorf("invalid postID %q in filename: %s", postID, filename)
	}

	// Read HTML content
	content, err := os.ReadFile(filePath)
	if err != nil {
		return PostInfo{}, fmt.Errorf("read file %s: %w", filePath, err)
	}

	contentStr := string(content)

	// Use same regex patterns as ParseIndexHTML
	subredditPattern := regexp.MustCompile(`<span\s+class="subreddit"[^>]*>r/([^<]+)</span>`)
	userPattern := regexp.MustCompile(`<span\s+class="user"[^>]*>u/([^<]+)</span>`)

	// Extract subreddit (use empty string if not found)
	var subreddit string
	if subMatch := subredditPattern.FindStringSubmatch(contentStr); len(subMatch) >= 2 {
		subreddit = subMatch[1]
	}

	// Extract username (use empty string if not found)
	var username string
	if userMatch := userPattern.FindStringSubmatch(contentStr); len(userMatch) >= 2 {
		username = userMatch[1]
	}

	// Determine if this is a user post
	isUserPost := strings.HasPrefix(subreddit, "u_")

	return PostInfo{
		PostID:     postID,
		Subreddit:  subreddit,
		Username:   username,
		IsUserPost: isUserPost,
	}, nil
}

// ParseHTMLFiles walks through a directory and parses all .html files to build a comprehensive PostMap.
//
// The function extracts POSTID from each filename (e.g., "1r4wjj5.html" → "1r4wjj5")
// and calls ParseHTMLFile for each .html file to extract post metadata.
//
// Progress is logged every 1,000 files. Errors are handled gracefully - corrupted HTML
// files are logged as warnings but do not stop processing.
//
// Returns error only if the directory cannot be read.
func (p *HTMLParser) ParseHTMLFiles(ctx context.Context, htmlDir string) error {
	p.PostMap = make(map[string]PostInfo)
	fileCount := 0

	err := filepath.Walk(htmlDir, func(path string, info os.FileInfo, err error) error {
		if err := ctx.Err(); err != nil {
			return err
		}

		if err != nil {
			slog.Warn("Error accessing path", "path", path, "error", err)
			return nil
		}

		if info.IsDir() {
			return nil
		}

		if !strings.HasSuffix(strings.ToLower(info.Name()), ".html") {
			return nil
		}

		postInfo, err := p.ParseHTMLFile(ctx, path)
		if err != nil {
			slog.Warn("Failed to parse file", "path", path, "error", err)
			return nil
		}
		p.PostMap[postInfo.PostID] = postInfo

		fileCount++
		if fileCount%1000 == 0 {
			slog.Info("Parsed files", "count", fileCount)
		}

		return nil
	})

	if err != nil {
		return fmt.Errorf("failed to walk directory %s: %w", htmlDir, err)
	}

	slog.Info("Completed parsing HTML files", "count", fileCount, "directory", htmlDir)
	return nil
}
